### ISSUE TITLE
Port Is listening but i can't ping/use it 

### ISSUE THREAD

**Issue by cod3r-dev** [concision/docker-windscribe-socks-server#1] opened 2020-01-28 21:09 UTC
The container start with success but i can't access the port

![image](https://user-images.githubusercontent.com/9705923/73305564-0269d400-4223-11ea-9e87-affcb71e6932.png)
![image](https://user-images.githubusercontent.com/9705923/73305597-14e40d80-4223-11ea-9661-8ea5ba3ccac9.png)
![image](https://user-images.githubusercontent.com/9705923/73305626-288f7400-4223-11ea-8002-c44710709956.png)

Any suggestion ?

**Comment by concision** [comment] 2020-01-28 22:05
Hi

This appears to be the expected logging output, so it seems likely to be some sort of networking misconfiguration.

A couple of inquiries:
- How are you trying to connect to the port?
- From where are you trying to access the port (e.g. locally, from another computer, etc)?
  - If accessing it remotely, are you sure that the port isn't firewalled?
- On the machine itself, can you run the following `curl` to test the connection and give me the output?

  ```bash
  curl -v -x socks5://localhost:1080 https://api.ipify.org
  ```

Thanks

**Comment by cod3r-dev** [comment] 2020-01-28 22:11
You have right i can get the vpn's ip from local network with 
`curl -v -x socks5://localhost:1080 https://api.ipify.org`

Any idea why i can't from outside? I haven't any firewall but i run already openvpn maybe thats the problem ?

Thanks for your reply!

**Comment by concision** [comment] 2020-01-28 22:39
If you have other networking services running, that might potentially conflict with accessing it. 

Can you provide some more detail about your setup and how you are trying to proxy your connections?

Are you running this on a remote server and trying to access it from your local machine?

**Comment by cod3r-dev** [comment] 2020-01-28 22:51
Yes i have one vps and i want to use the proxy to my local machine!
Its "iptables" conflict you are correct i cleaned all the rules 

`iptables -P INPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables -P OUTPUT ACCEPT
iptables -t nat -F
iptables -t mangle -F
iptables -F
iptables -X`

and now works!!

But not my openvpn  port forwards :) 

Hmmmm

**Comment by concision** [comment] 2020-01-28 23:01
I wouldn't recommend having the port publicly accessible, as anyone can use it without authentication. 

Are you running an OpenVPN server off of your VPS and connecting with an OpenVPN client on your local machine? If so, you should probably write an `iptables` rule to expose the 1080 port to only the tun networking interface, and drop it on your eth interface.

Let me know if this is resolved, and I'll close the issue.

**Comment by cod3r-dev** [comment] 2020-01-28 23:05
Yes for this solution i search for ;) ;) 

You can close the issue this is about my iptable config!!

**Closed as completed** 2020-01-28 23:13 UTC
Labels: question

**Comment by ronangaillard** [comment] 2020-05-07 06:01
I have the same issue : I can access the proxy using `localhost` but other machines on the local network can't access it.

What is the solution as I did not understand your answer ?

**Comment by concision** [comment] 2020-05-07 06:40
@ronangaillard This is likely not a project-specific issue, but a general networking/docker issue you are experiencing.

A few questions for you that are relevant:
- Are you publishing the port publicly on your machine?
- Are you using any Docker on Linux natively, or on other OS's like Windows/macOS?
- Are there any firewall rules/network configuration settings that prevent communication between local machines on your network?

**Comment by ronangaillard** [comment] 2020-05-07 06:43
`docker-ps` returns `f4ff865630a8        concisions/windscribe-socks-server:latest                        "/docker-entrypoint.…"   58 minutes ago      Up 58 minutes (healthy)   0.0.0.0:1080->1080/tcp   docker-windscribe-socks-server_windscribe_1`. I am not a docker expert but `0.0.0.0:1080` means its exposed publicly right ?

I am using Docker on Linux natively (Docker server on Linux, docker client on OSX)

`ufw` is disabled and no other firewall is running.

Do you have any hints ?

**Comment by concision** [comment] 2020-05-07 06:51
That definitely appears to be exposed publicly then.

Are you having any issues contacting other services (i.e. exposed services through a port) on the same Linux machine?

**Comment by ronangaillard** [comment] 2020-05-07 06:52
I had no problem, I even tried the `nginxdemos/hello` image to make sure it was working well. And port is exposed indeed with this image.

**Comment by ronangaillard** [comment] 2020-05-07 06:55
On the machine running the docker daemon : 

```bash
ronan@ubuntu-ronan:~$ curl --socks5 http://127.0.0.1:1080 ifconfig.co
xxx.xx.xxx.xxx
```

On the OSX running the docker client :
```bash
docker-windscribe-socks-server ❯ curl --socks5 192.168.2.73:1080 ifconfig.co
curl: (7) Failed to connect to 192.168.2.73 port 1080: Operation timed out
```

So the port is well opened. if not I would have a `Connection refused`

**Comment by concision** [comment] 2020-05-07 07:02
Sorry, to clarify - are you able to provably expose another service on your Docker Linux host and access that service from another machine? For example, running an NGINX server on your Docker Linux machine, and accessing it on your OSX machine?

**Comment by ronangaillard** [comment] 2020-05-07 07:05
Yes, I run the `nginxdemos/hello` image on my Linux machine, and I can access it on any machine on the local network using `http://192.168.2.73:32768`

**Comment by concision** [comment] 2020-05-07 07:06
Can you verify if this is still an issue for you with `concisions/windscribe-socks-server:0.1.0` (as opposed to `latest`, which is `0.2.0`)?

**Comment by ronangaillard** [comment] 2020-05-07 07:09
I have same issue with `0.1.0` yes

**Comment by concision** [comment] 2020-05-07 07:14
Hm, I must admit I am not totally sure what could be going wrong here, but it sounds definitely related to this project (sorry, initial assessment was wrong). This project was obnoxiously difficult to develop/test due to it's rather... odd networking setup (am not a networking expert).

Have you made any configurations to any iptables rules on your Linux machine? Perhaps it might be an existing conflicting iptables misconfiguration or iptables related issue. Windscribe requires manipulating them to function (hence some additional permissions are necessary in the docker run/docker-compose).

**Comment by ronangaillard** [comment] 2020-05-07 07:18
I am not a network expert neither 😋 

Here are my iptables : 
```
-P INPUT ACCEPT
-P FORWARD DROP
-P OUTPUT ACCEPT
-N DOCKER
-N DOCKER-ISOLATION-STAGE-1
-N DOCKER-ISOLATION-STAGE-2
-N DOCKER-USER
-A FORWARD -j DOCKER-USER
-A FORWARD -j DOCKER-ISOLATION-STAGE-1
-A FORWARD -o br-3f73667cae3f -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-3f73667cae3f -j DOCKER
-A FORWARD -i br-3f73667cae3f ! -o br-3f73667cae3f -j ACCEPT
-A FORWARD -i br-3f73667cae3f -o br-3f73667cae3f -j ACCEPT
-A FORWARD -o br-ceffab376f75 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-ceffab376f75 -j DOCKER
-A FORWARD -i br-ceffab376f75 ! -o br-ceffab376f75 -j ACCEPT
-A FORWARD -i br-ceffab376f75 -o br-ceffab376f75 -j ACCEPT
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -o br-417a707d3d37 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -o br-417a707d3d37 -j DOCKER
-A FORWARD -i br-417a707d3d37 ! -o br-417a707d3d37 -j ACCEPT
-A FORWARD -i br-417a707d3d37 -o br-417a707d3d37 -j ACCEPT
-A DOCKER -d 172.17.0.3/32 ! -i docker0 -o docker0 -p tcp -m tcp --dport 80 -j ACCEPT
-A DOCKER -d 172.18.0.2/32 ! -i br-417a707d3d37 -o br-417a707d3d37 -p tcp -m tcp --dport 8080 -j ACCEPT
-A DOCKER -d 172.20.0.2/32 ! -i br-ceffab376f75 -o br-ceffab376f75 -p tcp -m tcp --dport 8888 -j ACCEPT
-A DOCKER -d 172.23.0.2/32 ! -i br-3f73667cae3f -o br-3f73667cae3f -p tcp -m tcp --dport 1080 -j ACCEPT
-A DOCKER-ISOLATION-STAGE-1 -i br-3f73667cae3f ! -o br-3f73667cae3f -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-ceffab376f75 ! -o br-ceffab376f75 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i docker0 ! -o docker0 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -i br-417a707d3d37 ! -o br-417a707d3d37 -j DOCKER-ISOLATION-STAGE-2
-A DOCKER-ISOLATION-STAGE-1 -j RETURN
-A DOCKER-ISOLATION-STAGE-2 -o br-3f73667cae3f -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-ceffab376f75 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o docker0 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -o br-417a707d3d37 -j DROP
-A DOCKER-ISOLATION-STAGE-2 -j RETURN
-A DOCKER-USER -j RETURN
```

I do not fully understand them, but maybe you'll have an idea ?

This is becoming off topic but do you know how I could easily make another docker container access this proxy ? (I wanted to use http_proxy="http://192.168.2.37:1080" as an argument but this is not working as proxy is not accessible from the outside)

**Comment by concision** [comment] 2020-05-07 07:47
That looks fairly normal (as far as Docker iptables spam goes) and the 1080 port appears properly published. I can't imagine why your host machine is able to use the service properly, but another local machine is unable to access _specifically_ this service. :/ 

As for the proxy container question, after a bit of research, I believe a HTTP/HTTPS/FTP proxy server is necessary (and this service exposes only a SOCKS5 proxy). However, if you would like this as a feature, I can start to try adding support for in a week or two (graduating soon). This whole project is... quite a hack that I thought I'd share.

As for the underlying networking problem between your local network, I am not quite sure how to resolve it at this point. I am trying to replicate the issue on my local network, but it's the classic case of "it works on my machine". 

What OS/version and Docker version are you using? I can try to install them on a test machine and see if I can replicate the issue.

**Comment by ronangaillard** [comment] 2020-05-07 07:57
I am using Ubuntu Server 20.04

```bash
ronan@ubuntu-ronan:~$ docker -v
Docker version 19.03.8, build afacb8b7f0
```

I'm willing to help if needed :) 

I'm trying things such as `--env http_proxy="windscribe:1080" --env https_proxy="windscribe:1080" --net=docker-windscribe-socks-server_default `

I'll keep you posted ! Thanks for your time and help !

**Comment by concision** [comment] 2020-05-07 08:18
It'll take a bit to setup the test environment (download + installing), maybe a day or two. I can't imagine I'll have much luck reproducing the exact issue, but it's worth a shot and I have a spare machine. I take it you're using a mildly version of the docker-compose configuration?

And hm - I do not think you will have much luck with the `http_proxy` setup since this project is SOCKS5. I will investigate amending this sometime soon, as this seems like a practical use case.

**Comment by concision** [comment] 2020-05-08 04:59
Hi @ronangaillard,

I have managed to successfully recreate the issue with the installations you have. I am not exactly sure why this occurs, but **this definitely seems to confirm that it is project related and not a general networking issue**, as I had initially assumed.

I apologize for the slow response time, I am a bit preoccupied with academics at the moment. I will begin looking into a fix within the next week or so (as my academics will ramp down). Afterwards, I will look into a solution for using it as a docker-level proxy, as this seems like an interesting use case to support.

Would you mind opening a separate issue for better tracking?

**Comment by concision** [comment] 2020-09-08 12:37
@ronangaillard Late response, but I made several unsuccessful attempts over the few months to fix this networking issue. I was finally able to figure out a fix and applied a fix to the scripts.

I believe the issue should be resolved now and all external traffic should be accepted by the container. If it is still relevant, checkout the `latest` tag again (at the time of writing, version `0.3.0) and verify it works.
